---
title: "Abstract EVA"
author: "Kate Saunders"
date: "23/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Abstract:**

We know climate change to be influencing the distribution of temperature extremes. Given this, there has been much research on how the marginal parameters of univariate distributions, such as the generalised extreme value distribution, are changing temporally due to climate change. However temperature extremes, as with many environmental processes, are inherently spatio-temporal in nature. Therefore to truly understand how temperature extrema are changing with our changing climate, it is necessary to consider whether the spatial dependence between temperature extrema is also changing. In this talk, we present some preliminary results exploring if the spatial dependence between temperature extremes is changing. We consider both observational records and future projections of temperature.

<!-- It is well known that climate change influences the intensity of temperature extremes and heatwaves.  Traditional statistical approaches for modelling heat extremes however, often only consider how the distribution of extreme temperature is changing at a single location, such as station or grid point. For heatwaves, methods often aggregate spatially as opposed to modelling spatial dependence explicitly to consider the scale of the event. Given heatwaves are a large-scale spatial phenomena, approaches such as these only provide a partial picture of how temperature extremes are changing.  -->

<!-- To truly understand events such as heatwaves, we therefore need to understand the spatial-scale of these events and how the dependence between temperature maxima is affected by climate change. Given this, we work within an extreme value framework to model explicitly the changing extremal dependence between temperature maxima at pairs of locations. We present some initial work considering temperature maxima in Europe, using both observations and climate model data. Using our updated understanding of the dependence between temperature maxima, we then discuss the implications for processes like heatwaves. -->
